Added interfaces and tests
Dhii/config-interface pull request #1
Opened 2017-07-17 12:46 UTC by XedinUnknown

2017-07-17 12:48 UTC, mecha requested changes

2017-07-17 12:48 UTC, mecha commented on src/Exception/NotFoundExceptionInterface.php
> +interface NotFoundExceptionInterface extends
Consider allowing retrieval of the key that was not found.

2017-07-17 12:48 UTC, mecha commented on src/ConfigInterface.php
> +     * @param string|Stringable $key The config key.
Missing an `{@inheritdoc}`. Is this intentional?

2017-07-17 12:50 UTC, XedinUnknown commented on src/Exception/NotFoundExceptionInterface.php
> +interface NotFoundExceptionInterface extends
`Dhii\Data\Container\Exception\NotFoundExceptionInterface`

2017-07-17 12:50 UTC, XedinUnknown commented on src/ConfigInterface.php
> +     * @param string|Stringable $key The config key.
Most likely missing

2017-07-17 12:51 UTC, mecha commented on src/Exception/NotFoundExceptionInterface.php
> +interface NotFoundExceptionInterface extends
Oh my bad. I thought it was extended the PSR-11 `NotFoundExceptionInterface`.

2017-07-25 12:57 UTC, XedinUnknown commented
@mecha, it appears that right now `getValue()` return type is dependent on the internal storage of the configuration. This should not happen. Can we agree that the value will always be a string? Does this make sense to you? It would solve the problem of consumers having to cast the value twice in many cases.

2017-07-25 13:01 UTC, mecha commented
@XedinUnknown Yes. Perhaps also consider `StringableInterface`.

2017-07-25 13:22 UTC, XedinUnknown commented
@mecha, you mean [like this](https://github.com/Dhii/config-interface/blob/ef5394a0abc36cb0bab7fc5eb8b20bd56d7e10bb/src/ConfigInterface.php#L23)?

2017-07-25 14:36 UTC, mecha commented
@XedinUnknown No, I meant `getValue(): string|StringableInterface`.

2017-07-26 10:45 UTC, XedinUnknown commented
In my comment, I explain that `getValue(): string` solves the problem of having to cast prior to any conversion, Allowing it to return `StringableInterface` does not solve that, @mecha.

2017-07-26 10:49 UTC, mecha commented
Fair point.

2017-07-26 10:50 UTC, XedinUnknown commented
And if what's inside is a hierarchy, convert to JSON?

2017-07-26 11:07 UTC, mecha commented
I would favor whatever yields best performance in this case. If the hierarchy consists of plain arrays, JSON encoding and decoding is faster. If the hierarchy contains objects, PHP's serializing and unserializing is faster.

2017-07-26 11:09 UTC, XedinUnknown commented
@mecha, because no consumer should care or even be able to know what the structure actually is, going with that logic would make the return format unpredictable.

2017-07-26 11:12 UTC, mecha commented
I didn't mean that the format would be determined based on the contents of the hierarchy. Rather, we pick a form of serializing, either PHP's or JSON, based on what is more likely to be the case.

2017-07-26 11:13 UTC, XedinUnknown commented
@mecha, I don't think that one of them is more likely. I suggest we pick based on what is more useful. IMHO, that's JSON.

2017-07-26 11:19 UTC, mecha commented
@XedinUnknown I think serializing can be more useful. 

1. JSON does not include non-public data, resulting in loss of state
2. Serializing is almost always faster based on benchmarks
3. Objects can choose how to serialize or re-hydrate themselves

2017-07-26 11:26 UTC, XedinUnknown commented
@mecha, the result of `getValue()` does not need to know non-public data. In fact, it does not need to know any data that is not key and value data.

2017-07-26 11:30 UTC, mecha commented
@XedinUnknown Ok. Then if points 2 and 3 are not a concern, feel free to use JSON.

2017-07-26 11:33 UTC, XedinUnknown commented
Speed is certainly a concern. However, it's better to have a useful result slower, rather than a useless result faster. What are you gona do with your serialization result? You're not gona send it to client, or store it in DB, because nowadays JSON is used for that. 

As for point 3, like I wrote, there's no need for objects to re-hydrate themselves, because config consumers don't and shouldn't and cannot care about what kind of objects are inside the config.

2017-08-11 07:44 UTC, merged